### ISSUE TITLE
In collapsed view menu button is invisible.

### ISSUE THREAD

**Issue by MrLokans** [MrLokans/teamspark_template_task#5]
![2015-10-19 19-01-27](https://cloud.githubusercontent.com/assets/6051429/10583125/e6cc2fea-7693-11e5-83de-5c1f1f582a58.png)
![2015-10-19 19-01-38](https://cloud.githubusercontent.com/assets/6051429/10583126/e6f051fe-7693-11e5-843d-f5475192dfca.png)

**Comment by Shpilevskiy** [comment]
it happens because navbar-inverse class has been deleted to change background color and fix link style.
